### PR TITLE
Fix #426 hardcoded file name which broke file minification/concatenation

### LINKED ISSUE #426: CircularJSON error related to Blob code if concatenated crypton.js file is used
If you use a concatenated crypton.js.min file as created by the build process it throws an error:

ReferenceError: Can't find variable: CircularJSON

It gets thrown from at least this line of Blob related code:
https://github.com/SpiderOak/crypton/blob/264d13bc3bab99187f1e8bfe57cb4059d83c3293/client/src/vendor/isomer.js#L98

Until this is resolved you cannot apparently concatenate crypton JS files into a larger project.

This is likely related to CircularJSON being out of scope:
http://stackoverflow.com/questions/11219775/global-variable-in-web-worker

I don't yet understand why it works when the plain generated crypton.js file is pulled into a browser but fails when the concatenated version is used. The two should in theory be functionally identical.

Circular JSON was added in the following commit to solve other issues:
https://github.com/SpiderOak/crypton/commit/a9dcf7ac87df080e0f0e924b405d9d8250559d16
https://github.com/SpiderOak/crypton/pull/402

### PR DESCRIPTION
**Pull request by grempe**
This fixes the issue in my local testing and should work across all browsers.

### CODE REVIEW

File: client/src/core.js [hunk 1]
```diff
@@ -22,6 +22,18 @@ var crypton = {};
...
 
 /**!
+ * ### scriptName
+ * Holds the URL of the script that contains this code.
+ * This will be used by the 'isomerize' function and can be
+ * removed if it is removed.
+ */
+if (document && document.getElementsByTagName) {
+  var scripts = document.getElementsByTagName('script');
+  var script = scripts[scripts.length-1].src
```
Comment (daviddahl) [inline client/src/core.js]: Maybe I need more coffee, but, how are you sure this index is the crypton-containing script?

Comment (grempe) [inline client/src/core.js]: Because it's being run in the runtime at this moment and no other script
should load at the same time. This is just grabbing the last script path in
the array which is the one being currently executed.

It's a hack, but seems to be working reliably so far (Better than hard
coded script name). Another alternative would require a user to set a
variable which contains the name of the script. Which is a pain since you
would have to explicitly initialize crypton with that value or it would
fail. I could not find another way to associate running code with the name
of the file it was loaded from the browser with.

Better solution is to not do this isomerism hack (which is creating script
loading tags as strings and injecting them into the worker) somehow. I
don't have a good enough handle on web workers yet to offer a more
permanent solution.

Comment (daviddahl) [inline client/src/core.js]: Ok, this does work for now.

 I fear when if might not because of some browser bug or different implementations, in which case we could require the dev to set a variable (starting with a sensible default) and throw our own very explicit Exception when things are incorrectly configured.

**Comment by grempe** [comment]
I agree with your concerns as well.

I think the things I worry about right now related to this code is:

- what happens if you load a script async alongside other scripts?  Will the script array be a reliable way to identify the parent file of the crypton code?
- is the import code that is injected by isomerize causing another HTTP request to this path for the entire script? (good question for both old approach and new).
- are there negative consequences for 'isomerizing' a larger concatenated script which has lots of code unrelated to crypton? (good question for old approach and new, loading tons of unnecessary functions into the worker that will never be used?)

The fix for this long term has got to be not using this way of injecting the code into isomerize. but somehow selectively loading functions into the web worker directly instead of re-parsing and importing an entire script.  I'll try to look into it.

**Comment by devgeeks** [comment]
Isomerize should be the first against the wall when the revolution comes.

**Comment by daviddahl** [comment]
:+1:  yeah, its probably not good to run isomerize in web content AT ALL
